# Generated by Django 4.1.6 on 2023-02-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_remove_userdetails_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default='', max_length=300),
        ),
    ]
