# Generated by Django 4.1.6 on 2023-02-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_userdetails_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
