# Generated by Django 4.1.6 on 2023-02-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_alter_userdetails_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
    ]
