# Generated by Django 4.1.6 on 2023-02-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_userdetails_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
    ]
