# Generated by Django 4.1.6 on 2023-04-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_userdetails_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petType', models.CharField(max_length=10)),
                ('petName', models.CharField(max_length=30)),
                ('vaccinationStatus', models.BooleanField()),
                ('gender', models.CharField(max_length=10)),
                ('neutered', models.BooleanField()),
                ('shotsUptoDate', models.BooleanField()),
                ('goodWithKids', models.BooleanField()),
                ('goodWithDogs', models.BooleanField()),
                ('goodWithCats', models.BooleanField()),
                ('reason', models.CharField(max_length=500)),
                ('additionalInformation', models.CharField(max_length=500)),
            ],
        ),
    ]
