# Generated by Django 4.1.6 on 2023-04-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_dogadoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DogAdoption',
        ),
    ]
