# Generated by Django 4.1.6 on 2023-04-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_dogadoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogadoption',
            name='breed',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
