# Generated by Django 4.1.6 on 2023-04-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_dogadoption_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogadoption',
            name='city',
            field=models.CharField(default='Bhopal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogadoption',
            name='contactNumber',
            field=models.CharField(default='8972188695', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogadoption',
            name='currentOwnerName',
            field=models.CharField(default='Aditya', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogadoption',
            name='pinCode',
            field=models.CharField(default='560100', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogadoption',
            name='state',
            field=models.CharField(default='mh', max_length=100),
            preserve_default=False,
        ),
    ]
