# Generated by Django 4.1.6 on 2023-04-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_dogadoption_city_dogadoption_contactnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogadoption',
            name='pinCode',
        ),
    ]
